### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dom96** [oprypin/nim-csfml#15]
If not I will switch the Nimble packages link to my fork

**Comment by oprypin** [comment]
I certainly don't actively maintain this, e.g. the SFML version is outdated.
I'd accept pull requests though.

I have mixed feelings about changing the link. Transferring ownership would certainly make sense, but why to you in particular (and not some kind of community namespace, or even shared ownership while still under my name)?

**Comment by oprypin** [comment]
Yeah you know what, it certainly doesn't make sense to transfer it because the generator code is just impenetrable :sweat_smile:

**Comment by dom96** [comment]
as long as you're happy to be bugged about creating a release every so often then sure, we can do it under your name (or actually you can just give me write access to the repo if you prefer)

In any case, I'll create a PR for what I have.
