### ISSUE TITLE
Unable to change vertex properties?

### ISSUE THREAD

**Issue by Skaruts** [oprypin/nim-csfml#19]
Hi, I can't seem to be able to change the properties on vertices after I've created them. The code below gives me an error `'quads[idx + 0].color' cannot be assigned to`:

```
proc update_quad(x, y :int, alive:bool ) =
    var idx = (x+y*GW)*4    # GW is grid_width

    if alive:
        quads[idx+0].color = cell_color_alive
        quads[idx+1].color = cell_color_alive
        quads[idx+2].color = cell_color_alive
        quads[idx+3].color = cell_color_alive
    else:
        #(...)
```

To workaround this I have to recreate all the vertices:
```
    if alive:
        quads[idx+0] = vertex(quads[idx+0].position, cell_color_alive )
        quads[idx+1] = vertex(quads[idx+1].position, cell_color_alive )
        quads[idx+2] = vertex(quads[idx+2].position, cell_color_alive )
        quads[idx+3] = vertex(quads[idx+3].position, cell_color_alive )
```

But I suppose this solution is not as efficient. 

Am I doing something wrong or is this a limitation of nim-csfml that has slipped through or something?

**Comment by caldur** [comment]
If `quads` is array or seq of Vertex then obviously it has to be `var`

If `quads` is a `VertexArray` then I'd assume that's a nim-csfml problem - the wrapper of `[]` operator returns an r-value `Vertex` object and `[]=` operator only takes a `Vertex` as parameter.

The easy way would be to use the raw `VertexArray.getVertex` proc which returns a 'ptr Vertex', which you can the deref and change the fields:

`
#note the [] deref after indexing
quads.getVertex[idx+0][].color = cell_color_alive
`

Of course you can then use templates or overloading to make it look nicer...

**Comment by Skaruts** [comment]
yea, quads is a VertexArray. I followed your advice and [switched it](https://github.com/Skaruts/Game-of-Life-in-Multiple-Languages/blob/master/Nim/cellmap.nim#L28) to 
```
proc update_quad(idx:int, color:Color ) =
    quads.getVertex(idx+0)[].color = color
    quads.getVertex(idx+1)[].color = color
    # ...
```

It's running quite a bit faster now, I wasn't expecting such a big improvement. Surprisingly -- for me at least -- it's giving me just about the same frame rates as my C++ version. :)

**Comment by Skaruts** [comment]
Taking the liberty to close this, as my issue has long been solved.
