### ISSUE TITLE
Draw overload for VertexBuffer is missing

### ISSUE THREAD

**Issue by Skaruts** [oprypin/nim-csfml#20]
There seems to be no [draw overload](https://github.com/oprypin/nim-csfml/blob/master/src/csfml/graphics.nim#L271) for VertexBuffer.

I took the liberty to try to fix it with #21.

**Comment by oprypin** [comment]
No, `nimble` installs the latest release (or *tag* really) which is still old

**Comment by Skaruts** [comment]
I see. When can I expect the next one?
